WIP: Added common chart
sigstore/helm-charts pull request #416
Opened 2022-11-15 06:11 UTC by sabre1041

## Description of the change

Adds a common chart of reusable partials

## Existing or Associated Issue(s)

#337 

## Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [x] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2022-11-17 14:46 UTC, flxw submitted a review, later dismissed
Looks good to me for for the start :)

2022-11-22 06:35 UTC, JAORMX requested changes
Getting this common chart makes a lot of sense to me and would be very useful. given that it's a chart that we'd depend on throughout the helm charts in this repo, I'd appreciate a README that describes the goal of the common chart as well as the macros it's defining.

2022-11-23 04:32 UTC, JAORMX approved these changes
🛳ship it

2022-12-16 18:03 UTC, sabre1041 commented
@cpanato @k4leung4 can you take a look and integrate?

2022-12-16 18:39 UTC, cpanato commented
> @cpanato @k4leung4 can you take a look and integrate?

sorry taking too long, let me review this early next week

2022-12-19 17:12 UTC, k4leung4 approved these changes
apologies for the delay

looks good to me

2023-01-17 11:00 UTC, cpanato approved these changes
thanks

2023-01-17 11:00 UTC, merged