FEAT#Allow Enable/Disable Kubernetes Service Links
sigstore/helm-charts pull request #477
Opened 2023-02-28 22:30 UTC by nkreiger

## Description of the change

This Change/Proposal, is to allow setting the enableServiceLinks boolean in a kubernetes deployment via the helm charts. This is kind of an obscure configuration ask.

This variable (true by default), will automatically map all the service names and hosts into the environment variables of a kubernetes deployment. However, there is a limit to this, and when that limit is hit, you get the error `too many args`, whenever a pod restarts or during a new deployment.

Honestly, not sure why the default is true, it should only effect you if you are not using the DNS name when interacting with other services, which is not the case here.

## Existing or Associated Issue(s)

## Additional Information

 

## Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2023-02-28 22:31 UTC, nkreiger commented
I wasn't sure if I should just keep this forked, or open a PR, if this is something to move forward with, I can do the checklist, let me know.

2023-03-17 19:20 UTC, sabre1041 requested changes
A few items that need to be added before we can look to integrate this feature:

* Instead of a dictionary called `serviceLinks`, what about a boolean called `serviceLinksEnabled` and use that conditional and value in the deployment?
* `Chart.yaml` version bump
* JSON Schema values update
* Chart dependencies need to be updated between the charts

Given that this change is spread across multiple charts, separating them out across multiple PR's would be a better approach given the fact that chart testing needs to be able to resolve them effectively

2023-03-17 19:22 UTC, nkreiger commented
hey @sabre1041 yep, mostly considered this a request, more of the "final" pr. I will spread these out, and use the same strategy [here](https://github.com/bitnami/charts/commit/0f9a159c38b7a4ce693de79e243f6ee050275fdd) with the dictionary boolean

2026-06-05 20:46 UTC, cmurphy commented
This hasn't been updated in 3 years, I'm going to go ahead and close it but feel free to reopen it if this is something you still want to work on.

2026-06-05 20:46 UTC, closed without merging