Volume/Volume Mounts for Policy Webhook
sigstore/helm-charts pull request #478
Opened 2023-03-01 12:20 UTC by anderssonw

## Description of the change

Adds volume and volume mounts to the policy webhook deployment in the `policy-controller` chart. Uses the same structure for volume and volume mounts as the webhook deployment.

## Existing or Associated Issue(s)

No related issues.

## Additional Information

No idea how the JSON Schema is generated. Also some stuff was added into the README which I did not change. Presumably it was outdated.

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [x] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2023-03-01 12:59 UTC, cpanato commented
thanks for your PR @anderssonw 
can you please squash your commits and sign the DCO?

2023-03-01 16:15 UTC, hectorj2f commented on charts/policy-controller/README.md
> +| policywebhook.configData | object | `{}` |  |
let keep the old description ` Set the data of the `policy-config-controller` configmap`.

2023-03-01 16:16 UTC, hectorj2f reviewed
Let's keep the description to the field `configData`, otherwise it LGTM

2023-03-01 21:16 UTC, cpanato requested changes
+1 on the hectors comments

2023-03-02 16:37 UTC, hectorj2f approved these changes

2023-03-02 18:07 UTC, merged