optional SA creation
sigstore/helm-charts pull request #481
Opened 2023-03-06 19:51 UTC by prudnitskiy

## Description of the change

This MR allows changing of serviceAccount creation for policy-controller:
- allow disabling serviceAccount creation
- allows changing serviceAccount name

## Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [X] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [?] JSON Schema generated.
- [?] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2023-03-06 20:00 UTC, hectorj2f requested changes

2023-03-06 20:00 UTC, hectorj2f commented on charts/policy-controller/README.md
> -| webhook.image.version | string | `"sha256:947693aa3a536992bc89f3c7ded8a7707b26cd4518972f293edd3e57e112438e"` | `"v0.7.0"` |
please, keep the `v0.7.0` description

2023-03-06 20:00 UTC, hectorj2f commented on charts/policy-controller/README.md
> -| policywebhook.configData | object | `{}` | Set the data of the `policy-config-controller` configmap |
please, keep this description too.

2023-03-07 13:57 UTC, prudnitskiy commented on charts/policy-controller/README.md
> -| policywebhook.configData | object | `{}` | Set the data of the `policy-config-controller` configmap |
Updated.

2023-03-07 13:57 UTC, prudnitskiy commented on charts/policy-controller/README.md
> -| webhook.image.version | string | `"sha256:947693aa3a536992bc89f3c7ded8a7707b26cd4518972f293edd3e57e112438e"` | `"v0.7.0"` |
Updated

2023-03-07 15:43 UTC, hectorj2f commented on charts/policy-controller/README.md
> +| policywebhook.image.version | string | `"sha256:3a3581032ff69991ddd9f19faf8acd059c8fb0ba8d3b0164a13b99a096880c84"` |  |
v0.7.0 is still missing here :).

2023-03-07 15:43 UTC, hectorj2f commented on charts/policy-controller/README.md
> +| policywebhook.image.version | string | `"sha256:3a3581032ff69991ddd9f19faf8acd059c8fb0ba8d3b0164a13b99a096880c84"` |  |
the rest lgtm.

2023-03-07 17:00 UTC, hectorj2f submitted a review, later dismissed

2023-03-07 17:00 UTC, hectorj2f commented
One last thing, please sign off your commits :).

2023-03-07 17:01 UTC, prudnitskiy commented on charts/policy-controller/README.md
> +| policywebhook.image.version | string | `"sha256:3a3581032ff69991ddd9f19faf8acd059c8fb0ba8d3b0164a13b99a096880c84"` |  |
fixed, thank you

2023-03-07 17:20 UTC, hectorj2f approved these changes

2023-03-07 17:20 UTC, merged