feat: #546 Make mysql pvc volume name configurable
sigstore/helm-charts pull request #547
Opened 2023-06-13 22:27 UTC by jonathan-dorsey

## Description of the change

Adds the ability to optionally configure the volume name for the mysql pvc. This allows `helm upgrade --force` to be used after the initial deployment. 

## Existing or Associated Issue(s)

Closes #546 

## Additional Information
```
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 trillian => (version: "0.3.0", path: "charts/trillian")
------------------------------------------------------------------------------------------------------------------------

"sigstore" already exists with the same configuration, skipping
Linting chart "trillian => (version: \"0.3.0\", path: \"charts/trillian\")"
Checking chart "trillian => (version: \"0.3.0\", path: \"charts/trillian\")" for a version bump...
Old chart version: 0.2.5
New chart version: 0.3.0
Chart version ok.
Validating /Users/jonathand/src/helm-charts/charts/trillian/Chart.yaml...
Validation success! 👍
==> Linting charts/trillian
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ trillian => (version: "0.3.0", path: "charts/trillian")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```
## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [x] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [x] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2023-06-14 11:49 UTC, cpanato commented on charts/trillian/README.md
> +| mysql.gcp.cloudsql.version | string | `"sha256:c378a623353ee9c592795c0ad9e448bdc7e26c7635ba982968a60d0e3bb4d575"` | crane digest gcr.io/cloudsql-docker/gce-proxy:1.33.7 |
please revert this change

2023-06-14 11:49 UTC, cpanato commented on charts/trillian/README.md
> +| mysql.image.version | string | `"sha256:c04753ed44eac715e3191dad16fb0848a06714ddcb00c6f7768bf065485e1f8d"` | crane digest gcr.io/trillian-opensource-ci/db_server:v1.5.2 |
please revert this change

2023-06-14 11:53 UTC, cpanato requested changes
thanks, have small nit request
and did you tests the force with this change? can you provide a log or something?

2023-06-14 17:54 UTC, jonathan-dorsey commented on charts/trillian/README.md
> +| mysql.image.version | string | `"sha256:c04753ed44eac715e3191dad16fb0848a06714ddcb00c6f7768bf065485e1f8d"` | crane digest gcr.io/trillian-opensource-ci/db_server:v1.5.2 |
Updated!

2023-06-14 17:54 UTC, jonathan-dorsey commented on charts/trillian/README.md
> +| mysql.gcp.cloudsql.version | string | `"sha256:c378a623353ee9c592795c0ad9e448bdc7e26c7635ba982968a60d0e3bb4d575"` | crane digest gcr.io/cloudsql-docker/gce-proxy:1.33.7 |
Updated!

2023-06-15 13:35 UTC, jonathan-dorsey commented
> thanks, have small nit request and did you tests the force with this change? can you provide a log or something?

I did test with the change and it seems to work - sort of. I was kind of hoping if you provided a volume name that it would dynamically create the volume when necessary with that name, but that doesn't appear to be the case. Instead, when a volume name is given, it expects that volume to already exist. So as long as you have a volume with that name - it works. If you don't - the pvc stays in a pending state and the app never comes up. 

I could add a persistent volume resource to the chart and have it be created conditionally. Or just leave the expectation that if a volume name is specified then something else needs to create the volume in order for the chart to work. Any strong opinions?

2023-06-20 21:49 UTC, jonathan-dorsey commented
Well.... I ran into other problems manually creating the persistent volume in order to pass in a volume name. I'm going to go ahead and abandon this PR and corresponding issue in favor of not using the --force flag. That seems to be a better approach.

2023-06-20 21:49 UTC, closed without merging