add ingress create boolean
sigstore/helm-charts pull request #550
Opened 2023-06-15 21:55 UTC by cortesnoel-lm

## Description of the change

Adding .Values.ingress.create to tuf helm chart and wrapping tuf's ingress.yaml in an if block using that new "create" value. This way users can opt-in to tuf's ingress.yaml like some of the other chart objects.

## Existing or Associated Issue(s)

## Additional Information

 
Baiscally same pattern as tuf's namespace.yaml in templates dir. I left default value as true to not introduce breaking changes.

## Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [x] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [x] JSON Schema generated.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2023-06-16 14:09 UTC, cpanato requested changes
thanks
see a small nit and also sign the DCO

2023-06-16 14:09 UTC, cpanato commented on charts/tuf/README.md
> +Autogenerated from chart metadata using [helm-docs v1.11.0](https://github.com/norwoodj/helm-docs/releases/v1.11.0)
please drop this line

2023-06-22 17:24 UTC, cortesnoel-lm commented
Noting here, I made all the recommended changes and resolved the convos. Is there anything else needed from me to merge?

2023-06-23 07:08 UTC, hectorj2f approved these changes

2023-06-23 07:09 UTC, cpanato approved these changes

2023-06-23 07:09 UTC, merged