Bump fulcio chart for ctlog
sigstore/helm-charts pull request #75
Opened 2022-03-22 14:40 UTC by sabre1041

Bumping fulcio chart for ctlog version update

2022-03-22 17:05 UTC, cpanato requested changes
you also will need to bump the chart version

2022-03-22 17:21 UTC, sabre1041 commented
@cpanato bumped

2022-03-22 17:24 UTC, cpanato commented
github is dead lol 
lets wait

2022-03-23 08:43 UTC, cpanato approved these changes

2022-03-23 08:43 UTC, merged