bump policy-controller to v0.11.0
sigstore/helm-charts pull request #870
Opened 2024-12-11 21:40 UTC by hectorj2f

## Description of the change

Bump policy-controller to use v0.11.0

2024-12-12 09:48 UTC, cpanato commented
@hectorj2f need to update the readme

2024-12-12 09:48 UTC, cpanato requested changes
readme update

2024-12-12 11:31 UTC, cpanato requested changes
version is not quite right

2024-12-12 11:59 UTC, hectorj2f commented on charts/policy-controller/Chart.yaml
> +version: 0.11.0
Generally I was thinking to match the app version here considering we skipped couple of versions in between.

2024-12-12 13:06 UTC, cpanato commented on charts/policy-controller/Chart.yaml
> +version: 0.11.0
the chart version should not be equal to the app verision, the chart will have other updates that is not related to the app release

but for this case that we are bumping the minor of PC we can bump he minor in the chart version, but not matching the versions

2024-12-16 19:21 UTC, avo-sepp commented
Bumping this PR. Would really like to see it completed. 

If the version of 0.11.0 ends up as 0.8 in the Helm chart, do you plan on releasing versions 0.7->0.10 and if so, what Helm chart versions would those get?

2024-12-17 17:09 UTC, cpanato approved these changes

2024-12-17 17:09 UTC, merged