bump scaffold version for new rekor/fulcio version
sigstore/helm-charts pull request #90
Opened 2022-04-01 15:11 UTC by k4leung4

Signed-off-by: Kenny Leung <kleung@chainguard.dev>

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2022-04-01 15:22 UTC, cpanato requested changes
you need to bump the versions for each chart in a different PR, otherwise when the release happens will break it because we don't know if the fulcio/rekor will run first and scafold will run in the end

can you split it? but the question is why just bump fulcio/rekor with no changes

2022-04-01 15:23 UTC, k4leung4 commented
i was thinking i need bump the version when changing dependency version, I guess that is not needed?

2022-04-01 15:25 UTC, cpanato commented
i think it is all using the latest charts, looks like this PR is not needed

2022-04-04 07:18 UTC, cpanato approved these changes

2022-04-04 07:18 UTC, merged